site_name: Strapi Documentation
repo_url: https://github.com/pwizla/strapi-docs-material-mkdocs-poc
edit_uri: edit/main/docs
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    - navigation.prune
    - navigation.top
    - header.autohide
    - toc.follow
    - content.tabs.link # link all tabs with the same label throughout whole docs (test it with JS/TS tabs)
  palette:
   # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  # - git-authors
  - git-committers: # using ojacques version of the plugin - https://github.com/ojacques/mkdocs-git-committers-plugin-2
      repository: pwizla/strapi-docs-material-mkdocs-poc
      branch: main
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: "100%"
      height: auto
      zoomable: true
      draggable: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true # mandatory for tabs to work — see https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
  - pymdownx.highlight:
      anchor_linenums: true # make it possible to link to a specific line of code
      use_pygments: true # renders colors on server side, not on client side
  - pymdownx.inlinehilite
  - attr_list # used for annotations and images — see https://squidfunk.github.io/mkdocs-material/reference/annotations/#annotations
  - md_in_html # same, required for annotations and images
  - toc:
      permalink: true
      # toc_depth: 4 # uncomment and define a number from 1 to 6 — see https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.toc_depth
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  status:
    new: ✨ New in Strapi v4.4.0!
  # analytics:  # commented out until we have authorization to use the tracking id
  #   provider: google
  #   property: UA-54313258-1
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >- 
  #           Thanks for your feedback! Help us improve this page by
  #           using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
