site_name: Strapi Documentation
repo_url: https://github.com/pwizla/strapi-docs-material-mkdocs-poc
edit_uri: edit/main/docs
theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.top
    - header.autohide
    - toc.follow
  palette:
   # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-5
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - git-committers:
      repository: pwizla/strapi-docs-material-mkdocs-poc
      token: !ENV GH_TOKEN
      branch: main
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
